# Week 4 Short Answer Questions

## Noah Zwiefel

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

8.1.

a. 2
b. 2
c. 1
d. 5
e. 3
f. 4.
g. 2.
h. 5

8.2:

1.
ggplot(CPS85, aes(x=age,y=wage)) + geom_point(aes(shape=married)) + facet_wrap( ~sector)
2.
ggplot(CPS85, aes(x=age,y=wage)) + geom_point() + facet_wrap(married ~ sex)

8.3

a. 

ggplot(CPS85, aes(x=age,y=wage)) + geom_point()

b.

ggplot(CPS85, aes(x=age,y=wage)) + geom_point(aes(shape=sex))

c.
ggplot(CPS85, aes(x=age,y=wage)) + geom_point(aes(shape=sex)) + facet_wrap(~married)

d.

ggplot(CPS85, aes(x=age,y=wage)) + geom_point(aes(shape=married))



9.1:

a. I'd guess transformation: transforms into str() type. or quick presentation.
b. data verb (table in->table out)
c. data verb (table in->table out)
d. reduction verb (not an option in this list, but that's what it is...)
e. data verb (table in->table out)
f. summary function
g. summary function
h. data_verb
i. reduction verb/quick presentation? prints out data in console..

9.3

1.

diamonds %>% 
  group_by(color) %>% 
  summarise(avg_carat_size=mean(carat)) %>% 
  arrange(desc(avg_carat_size)) %>% 
  head( 1 )

2.

diamonds %>% 
  group_by(clarity) %>% 
  summarise(avg_table_size=mean(table)) %>% 
  arrange(desc(avg_table_size)) %>% 
  head( 1 )
