# Week 4 Project

## Noah Zwiefel

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

1.

``` {r}
library(mosaicData)
DailyBirths <- Birthdays %>% group_by(date) %>% summarise(birthcount=sum(births))

ggplot(data=DailyBirths, aes(x=date, y=birthcount)) + geom_point()
```

2.

a.

``` {r}
DailyBirths <- Birthdays %>% mutate(which_week=week(date)) %>% group_by(which_week) %>% summarise(birthcount=sum(births))

ggplot(data=DailyBirths, aes(x=which_week, y=birthcount)) + geom_point()

```

b.
``` {r}
DailyBirths <- Birthdays %>% mutate(which_month=month(date)) %>% group_by(which_month) %>% summarise(birthcount=sum(births))

ggplot(data=DailyBirths, aes(x=which_month, y=birthcount)) + geom_point()
```

c.
``` {r}
DailyBirths <- Birthdays %>% mutate(which_day=yday(date)) %>% group_by(which_day) %>% summarise(birthcount=sum(births))

ggplot(data=DailyBirths, aes(x=which_day, y=birthcount)) + geom_point()

```

3.

``` {r}
DailyBirths <- Birthdays %>% mutate(which_day_of_week=wday(date, label=TRUE)) %>% group_by(which_day_of_week) %>% summarise(birthcount=sum(births))

ggplot(data=DailyBirths, aes(x=which_day_of_week, y=birthcount)) + geom_point()

```

4.

``` {r}
MyTwoYears <- Birthdays %>% filter(year(date) >= 1982, year(date) <= 1983)  %>% mutate(which_day_of_week=wday(date, label=TRUE)) %>% group_by(date) %>% mutate(birthcount=sum(births))
ggplot(MyTwoYears, aes(x=date,y=birthcount,color=which_day_of_week)) + geom_point()
```

Looks like babies don't like being born on the weekend: also many of the babies were born in late 1982/1983. Fewer in Jan/Feb of each year.
