# Week 2 Short Answer Questions

## Noah Zwiefel

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

1.1.

a) Taffy: value of var for specific case

b) Year: quantitative (?)

c) sex: categorical

d) name: categorical

e) count: quantitative

1.2:

The var "number of states" has mostly quantitative values - however, it also has a case with the value "it depends". Additionally, for the var "in office", the majority of cases have the format YYYY-YYYY, whereas one case has the value YYYY to YYYY thus breaking the format. If one wanted to get really picky, they could suggest that the "in office" variable be split up into two vars - "entered office" and "left office". Finally, the "president" variable has inconsistant formatting: the first case has Last, First format, whereas the other two have a First Last format.

1.4

1. 

- variables in table A: year, algeria, brazil, columbia
- vars in table b: country, y2000, y2001
- vars in table c: country, year, value

2. 

- table a: a year
- table b: a country
- table c: a country in a year

1.5

1. It looks like there are 7.
2. It looks like each case represents an airport
3. faa, name, dst, tzone, tz, latlon are probably all categorical, while alt is likely quanitative.

2.2.

2. and 3.

2.3.

Current Population Survey


2.4.

an object is being named: the <- should probably be replaced with an = sign.

2.6.

1. Legit
2. legit
3. not legit: get rid of quotation marks
4. legit
5. not legit: get rid of space
6. legit
7. legit
8. legit
9. not legit: looks like a function

2.7

1. Looks like there's 19 vars. 
2. 336776 cases
3. each case is a specific flight that departed NYC 
4. 

- quantitative: year, month, day, dep_time, arr_time, sched_dep_time, sched_arr_time, dep_delay, arr_delay, hour, minute, air_time, distance, (likely) time_hour
- categorical: carrier, tailnum, flight, origin, dest,

5.

air_time = minutes

distance = miles

2.8

1. b.
2. d.
3. a.
4. c
5. e

2.9

- Used in object name: . _ - 
- Used in a string: any of them!

2.10

- CountryData: 76 variables
- Mass of trunk fat
- 23018
- count
- DEM = democratic, LIB = libertarian, REP = republican, UNA = unaffilated

3.1

1. fireplace <- fireplace %>% filter(on="YES")
2. fireplace()
3. warmth(fireplace="YES")
4. fireplace + 5

3.2:

It's using chaining/ the %>% symbol incorrectly -> the syntax is wrong: there should be something for that command to apply the right side to the left side: instead it's simply being saved in an object.

3.3:

Wrong symbol: we want to check for equality, not assign a string to a variable/object.

3.4:

1. b
2. a
3. d
4. d (kinda)
5. a.
6. c
7. c
8. a
9. c
10. a
11. c
12. a
13. a
14. c
15. c
16. a
17. c
18. a
19. c

3.5

- brain weight in kg
- 83 cases
- each case is an animal
- carnivore, omnivore, herbivore (in dataset refered to as "carni", "omni", and "herbi")

3.6

c. It'll find the mean not the sum...

4.1, 4.2, 4.3, 4.4, 4.5
